delete from orders
delete from OrderObjects 
set identity_insert OrderObjects on
insert into orderObjects (objectID,parentID,objectName) values('0','-1','ВотГЭС')
insert into orderObjects (objectID,parentID,objectName) values('1','0','Собственные нужды')
insert into orderObjects (objectID,parentID,objectName) values('2','1','Щиты СН')
insert into orderObjects (objectID,parentID,objectName) values('3','2','1Н')
insert into orderObjects (objectID,parentID,objectName) values('4','3','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('5','3','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('6','3','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('7','2','2Н')
insert into orderObjects (objectID,parentID,objectName) values('8','7','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('9','7','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('10','7','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('11','2','3Н')
insert into orderObjects (objectID,parentID,objectName) values('12','11','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('13','11','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('14','11','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('15','2','4Н')
insert into orderObjects (objectID,parentID,objectName) values('16','15','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('17','15','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('18','15','2 Секция ')
insert into orderObjects (objectID,parentID,objectName) values('19','2','8Н')
insert into orderObjects (objectID,parentID,objectName) values('20','19','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('21','19','1 Секция ')
insert into orderObjects (objectID,parentID,objectName) values('22','19','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('23','2','9Н')
insert into orderObjects (objectID,parentID,objectName) values('24','23','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('25','23','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('26','23','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('27','2','90Н')
insert into orderObjects (objectID,parentID,objectName) values('28','27','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('29','27','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('30','27','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('31','2','10Н')
insert into orderObjects (objectID,parentID,objectName) values('32','31','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('33','31','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('34','31','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('35','2','7Н')
insert into orderObjects (objectID,parentID,objectName) values('36','35','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('37','35','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('38','35','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('39','2','35Н')
insert into orderObjects (objectID,parentID,objectName) values('40','39','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('41','39','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('42','2','36Н')
insert into orderObjects (objectID,parentID,objectName) values('43','42','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('44','42','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('45','42','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('46','2','34Н')
insert into orderObjects (objectID,parentID,objectName) values('47','46','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('48','46','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('49','2','ТП-1')
insert into orderObjects (objectID,parentID,objectName) values('50','2','ТП-2')
insert into orderObjects (objectID,parentID,objectName) values('51','2','Резервный шинопровод')
insert into orderObjects (objectID,parentID,objectName) values('52','51','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('53','51','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('54','51','3 Секция')
insert into orderObjects (objectID,parentID,objectName) values('55','51','4 Секция')
insert into orderObjects (objectID,parentID,objectName) values('56','2','Испытательный шинопровод')
insert into orderObjects (objectID,parentID,objectName) values('57','2','21Н')
insert into orderObjects (objectID,parentID,objectName) values('58','2','22Н')
insert into orderObjects (objectID,parentID,objectName) values('59','2','23Н')
insert into orderObjects (objectID,parentID,objectName) values('60','2','24Н')
insert into orderObjects (objectID,parentID,objectName) values('61','2','25Н')
insert into orderObjects (objectID,parentID,objectName) values('62','1','Трансформаторы СН')
insert into orderObjects (objectID,parentID,objectName) values('63','62','21Т')
insert into orderObjects (objectID,parentID,objectName) values('64','62','22Т')
insert into orderObjects (objectID,parentID,objectName) values('65','62','23Т')
insert into orderObjects (objectID,parentID,objectName) values('66','62','24Т')
insert into orderObjects (objectID,parentID,objectName) values('67','62','25Т')
insert into orderObjects (objectID,parentID,objectName) values('68','62','26Т')
insert into orderObjects (objectID,parentID,objectName) values('69','62','27Т')
insert into orderObjects (objectID,parentID,objectName) values('70','62','28Т')
insert into orderObjects (objectID,parentID,objectName) values('71','62','29Т')
insert into orderObjects (objectID,parentID,objectName) values('72','62','30Т')
insert into orderObjects (objectID,parentID,objectName) values('73','62','31Т')
insert into orderObjects (objectID,parentID,objectName) values('74','62','32Т')
insert into orderObjects (objectID,parentID,objectName) values('75','62','33Т')
insert into orderObjects (objectID,parentID,objectName) values('76','62','34Т')
insert into orderObjects (objectID,parentID,objectName) values('77','62','35Т')
insert into orderObjects (objectID,parentID,objectName) values('78','62','36Т')
insert into orderObjects (objectID,parentID,objectName) values('79','62','37Т')
insert into orderObjects (objectID,parentID,objectName) values('80','62','38Т')
insert into orderObjects (objectID,parentID,objectName) values('81','62','7Т')
insert into orderObjects (objectID,parentID,objectName) values('82','62','8Т')
insert into orderObjects (objectID,parentID,objectName) values('83','62','ТВИ')
insert into orderObjects (objectID,parentID,objectName) values('84','1','КРУ-1')
insert into orderObjects (objectID,parentID,objectName) values('85','84','Секционный выключатель')
insert into orderObjects (objectID,parentID,objectName) values('86','84','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('87','86','Ячейка 1')
insert into orderObjects (objectID,parentID,objectName) values('88','86','Ячейка 2')
insert into orderObjects (objectID,parentID,objectName) values('89','86','Ячейка 3')
insert into orderObjects (objectID,parentID,objectName) values('90','86','Ячейка 4')
insert into orderObjects (objectID,parentID,objectName) values('91','86','Ячейка 5')
insert into orderObjects (objectID,parentID,objectName) values('92','86','Ячейка 6')
insert into orderObjects (objectID,parentID,objectName) values('93','86','Ячейка 7')
insert into orderObjects (objectID,parentID,objectName) values('94','86','Ячейка 8')
insert into orderObjects (objectID,parentID,objectName) values('95','86','Ячейка 9')
insert into orderObjects (objectID,parentID,objectName) values('96','86','Ячейка 10')
insert into orderObjects (objectID,parentID,objectName) values('97','86','Ячейка 11')
insert into orderObjects (objectID,parentID,objectName) values('98','86','Ячейка 12')
insert into orderObjects (objectID,parentID,objectName) values('99','84','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('100','99','Ячейка 13')
insert into orderObjects (objectID,parentID,objectName) values('101','99','Ячейка 14')
insert into orderObjects (objectID,parentID,objectName) values('102','99','Ячейка 15')
insert into orderObjects (objectID,parentID,objectName) values('103','99','Ячейка 16')
insert into orderObjects (objectID,parentID,objectName) values('104','99','Ячейка 17')
insert into orderObjects (objectID,parentID,objectName) values('105','99','Ячейка 18')
insert into orderObjects (objectID,parentID,objectName) values('106','99','Ячейка 19')
insert into orderObjects (objectID,parentID,objectName) values('107','99','Ячейка 20')
insert into orderObjects (objectID,parentID,objectName) values('108','99','Ячейка 21')
insert into orderObjects (objectID,parentID,objectName) values('109','99','Ячейка 22')
insert into orderObjects (objectID,parentID,objectName) values('110','99','Ячейка 23')
insert into orderObjects (objectID,parentID,objectName) values('111','99','Ячейка 24')
insert into orderObjects (objectID,parentID,objectName) values('112','1','КРУ-2')
insert into orderObjects (objectID,parentID,objectName) values('113','112','Секционный выключатель')
insert into orderObjects (objectID,parentID,objectName) values('114','112','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('115','114','Ячейка 1')
insert into orderObjects (objectID,parentID,objectName) values('116','114','Ячейка 2')
insert into orderObjects (objectID,parentID,objectName) values('117','114','Ячейка 3')
insert into orderObjects (objectID,parentID,objectName) values('118','114','Ячейка 4')
insert into orderObjects (objectID,parentID,objectName) values('119','114','Ячейка 5')
insert into orderObjects (objectID,parentID,objectName) values('120','114','Ячейка 6')
insert into orderObjects (objectID,parentID,objectName) values('121','114','Ячейка 7')
insert into orderObjects (objectID,parentID,objectName) values('122','112','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('123','122','Ячейка 8')
insert into orderObjects (objectID,parentID,objectName) values('124','122','Ячейка 9')
insert into orderObjects (objectID,parentID,objectName) values('125','122','Ячейка 10')
insert into orderObjects (objectID,parentID,objectName) values('126','122','Ячейка 11')
insert into orderObjects (objectID,parentID,objectName) values('127','122','Ячейка 12')
insert into orderObjects (objectID,parentID,objectName) values('128','122','Ячейка 13')
insert into orderObjects (objectID,parentID,objectName) values('129','122','Ячейка 14')
insert into orderObjects (objectID,parentID,objectName) values('130','1','Краны')
insert into orderObjects (objectID,parentID,objectName) values('131','130','Кран машзала №1')
insert into orderObjects (objectID,parentID,objectName) values('132','130','Кран машзала №2')
insert into orderObjects (objectID,parentID,objectName) values('133','130','Кран ВП 2*125')
insert into orderObjects (objectID,parentID,objectName) values('134','130','Полукозловой кран 2*150')
insert into orderObjects (objectID,parentID,objectName) values('135','130','Грейферный кран №1')
insert into orderObjects (objectID,parentID,objectName) values('136','130','Грейферный кран №2')
insert into orderObjects (objectID,parentID,objectName) values('137','130','Кран  2*63')
insert into orderObjects (objectID,parentID,objectName) values('138','130','Кран трансформаторной башни')
insert into orderObjects (objectID,parentID,objectName) values('139','1','СН генераторов')
insert into orderObjects (objectID,parentID,objectName) values('140','139','11Н')
insert into orderObjects (objectID,parentID,objectName) values('141','140','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('142','140','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('143','140','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('144','139','12Н')
insert into orderObjects (objectID,parentID,objectName) values('145','144','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('146','144','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('147','144','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('148','139','13Н')
insert into orderObjects (objectID,parentID,objectName) values('149','148','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('150','148','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('151','148','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('152','139','14Н')
insert into orderObjects (objectID,parentID,objectName) values('153','152','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('154','152','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('155','152','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('156','139','15Н')
insert into orderObjects (objectID,parentID,objectName) values('157','156','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('158','156','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('159','156','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('160','139','16Н')
insert into orderObjects (objectID,parentID,objectName) values('161','160','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('162','160','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('163','160','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('164','139','17Н')
insert into orderObjects (objectID,parentID,objectName) values('165','164','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('166','164','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('167','164','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('168','139','18Н')
insert into orderObjects (objectID,parentID,objectName) values('169','168','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('170','168','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('171','168','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('172','139','19Н')
insert into orderObjects (objectID,parentID,objectName) values('173','172','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('174','172','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('175','172','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('176','139','20Н')
insert into orderObjects (objectID,parentID,objectName) values('177','176','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('178','176','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('179','176','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('180','0','Главные трансформаторы')
insert into orderObjects (objectID,parentID,objectName) values('181','180','1Т')
insert into orderObjects (objectID,parentID,objectName) values('182','181','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('183','181','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('184','180','2АТГ')
insert into orderObjects (objectID,parentID,objectName) values('185','184','Фаза A')
insert into orderObjects (objectID,parentID,objectName) values('186','185','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('187','185','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('188','184','Фаза В')
insert into orderObjects (objectID,parentID,objectName) values('189','188','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('190','188','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('191','184','Фаза С')
insert into orderObjects (objectID,parentID,objectName) values('192','191','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('193','191','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('194','180','3АТГ')
insert into orderObjects (objectID,parentID,objectName) values('195','194','Фаза A')
insert into orderObjects (objectID,parentID,objectName) values('196','195','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('197','195','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('198','194','Фаза В')
insert into orderObjects (objectID,parentID,objectName) values('199','198','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('200','198','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('201','194','Фаза С')
insert into orderObjects (objectID,parentID,objectName) values('202','201','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('203','201','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('204','180','4Т')
insert into orderObjects (objectID,parentID,objectName) values('205','204','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('206','204','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('207','180','5АТ')
insert into orderObjects (objectID,parentID,objectName) values('208','207','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('209','207','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('210','180','6АТ')
insert into orderObjects (objectID,parentID,objectName) values('211','210','ШАОТ №1')
insert into orderObjects (objectID,parentID,objectName) values('212','210','ШАОТ №2')
insert into orderObjects (objectID,parentID,objectName) values('213','0','Оперативно-постоянный ток')
insert into orderObjects (objectID,parentID,objectName) values('214','213','1П')
insert into orderObjects (objectID,parentID,objectName) values('215','214','Панель 1')
insert into orderObjects (objectID,parentID,objectName) values('216','214','Панель 2')
insert into orderObjects (objectID,parentID,objectName) values('217','214','Панель 3')
insert into orderObjects (objectID,parentID,objectName) values('218','214','ВАЗП-1')
insert into orderObjects (objectID,parentID,objectName) values('219','214','УЗП-1')
insert into orderObjects (objectID,parentID,objectName) values('220','214','АБ-1')
insert into orderObjects (objectID,parentID,objectName) values('221','213','2П')
insert into orderObjects (objectID,parentID,objectName) values('222','221','Панель 1')
insert into orderObjects (objectID,parentID,objectName) values('223','221','Панель 2')
insert into orderObjects (objectID,parentID,objectName) values('224','221','Панель 3')
insert into orderObjects (objectID,parentID,objectName) values('225','221','Панель 4')
insert into orderObjects (objectID,parentID,objectName) values('226','221','УЗП-2')
insert into orderObjects (objectID,parentID,objectName) values('227','221','ВАЗП-2')
insert into orderObjects (objectID,parentID,objectName) values('228','221','АБ-2')
insert into orderObjects (objectID,parentID,objectName) values('229','213','3П')
insert into orderObjects (objectID,parentID,objectName) values('230','229','Панель 1')
insert into orderObjects (objectID,parentID,objectName) values('231','229','Панель 2')
insert into orderObjects (objectID,parentID,objectName) values('232','229','Панель 3')
insert into orderObjects (objectID,parentID,objectName) values('233','229','Панель 4')
insert into orderObjects (objectID,parentID,objectName) values('234','229','УЗП-3')
insert into orderObjects (objectID,parentID,objectName) values('235','229','ВАЗП-3')
insert into orderObjects (objectID,parentID,objectName) values('236','229','АБ-3')
insert into orderObjects (objectID,parentID,objectName) values('237','213','4П')
insert into orderObjects (objectID,parentID,objectName) values('238','237','Панель 1')
insert into orderObjects (objectID,parentID,objectName) values('239','237','Панель 2')
insert into orderObjects (objectID,parentID,objectName) values('240','237','Панель 3')
insert into orderObjects (objectID,parentID,objectName) values('241','237','УЗП-4')
insert into orderObjects (objectID,parentID,objectName) values('242','237','ВАЗП-4')
insert into orderObjects (objectID,parentID,objectName) values('243','237','АБ-4')
insert into orderObjects (objectID,parentID,objectName) values('244','0','Оперативно переменный ток')
insert into orderObjects (objectID,parentID,objectName) values('245','244','АБП-1')
insert into orderObjects (objectID,parentID,objectName) values('246','244','АБП-2')
insert into orderObjects (objectID,parentID,objectName) values('247','244','АБП-3')
insert into orderObjects (objectID,parentID,objectName) values('248','244','АБП-4')
insert into orderObjects (objectID,parentID,objectName) values('249','244','АБП-5')
insert into orderObjects (objectID,parentID,objectName) values('250','244','АБП-6')
insert into orderObjects (objectID,parentID,objectName) values('251','244','АБП-7')
insert into orderObjects (objectID,parentID,objectName) values('252','244','АБП-8')
insert into orderObjects (objectID,parentID,objectName) values('253','244','АБП-9')
insert into orderObjects (objectID,parentID,objectName) values('254','244','АБП-10')
insert into orderObjects (objectID,parentID,objectName) values('255','0','Здания и сооружения')
insert into orderObjects (objectID,parentID,objectName) values('256','255','Здание ГЭС')
insert into orderObjects (objectID,parentID,objectName) values('257','256','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('258','256','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('259','256','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('260','256','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('261','256','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('262','256','Маслохозяйство')
insert into orderObjects (objectID,parentID,objectName) values('263','262','Бак турбинного масла №1')
insert into orderObjects (objectID,parentID,objectName) values('264','262','Бак турбинного масла №2')
insert into orderObjects (objectID,parentID,objectName) values('265','262','Бак турбинного масла №3')
insert into orderObjects (objectID,parentID,objectName) values('266','262','Бак турбинного масла №4')
insert into orderObjects (objectID,parentID,objectName) values('267','262','Бак турбинного масла №5')
insert into orderObjects (objectID,parentID,objectName) values('268','262','Бак турбинного масла №6')
insert into orderObjects (objectID,parentID,objectName) values('269','262','Бак компрессорного масла №7')
insert into orderObjects (objectID,parentID,objectName) values('270','262','Бак индустриального масла №8')
insert into orderObjects (objectID,parentID,objectName) values('271','262','Бак трансформаторного масла №9')
insert into orderObjects (objectID,parentID,objectName) values('272','262','Бак трансформаторного масла №10')
insert into orderObjects (objectID,parentID,objectName) values('273','262','Бак трансформаторного масла №11')
insert into orderObjects (objectID,parentID,objectName) values('274','262','Бак трансформаторного масла №12')
insert into orderObjects (objectID,parentID,objectName) values('275','262','Бак трансформаторного масла №13')
insert into orderObjects (objectID,parentID,objectName) values('276','262','Бак трансформаторного масла №14')
insert into orderObjects (objectID,parentID,objectName) values('277','255','Вспомогательный корпус')
insert into orderObjects (objectID,parentID,objectName) values('278','277','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('279','277','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('280','277','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('281','277','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('282','277','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('283','277','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('284','255','Здание административно-управленческого персонала')
insert into orderObjects (objectID,parentID,objectName) values('285','284','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('286','284','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('287','284','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('288','284','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('289','284','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('290','284','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('291','255','Здание проходной')
insert into orderObjects (objectID,parentID,objectName) values('292','291','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('293','291','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('294','291','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('295','291','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('296','291','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('297','291','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('298','255','Столовая')
insert into orderObjects (objectID,parentID,objectName) values('299','298','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('300','298','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('301','298','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('302','298','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('303','298','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('304','298','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('305','255','Гараж')
insert into orderObjects (objectID,parentID,objectName) values('306','305','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('307','305','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('308','305','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('309','305','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('310','305','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('311','305','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('312','255','Теплица')
insert into orderObjects (objectID,parentID,objectName) values('313','312','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('314','312','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('315','312','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('316','312','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('317','312','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('318','312','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('319','255','Заготовительная мастерская')
insert into orderObjects (objectID,parentID,objectName) values('320','319','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('321','319','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('322','319','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('323','319','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('324','319','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('325','319','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('326','255','Столярная мастерская')
insert into orderObjects (objectID,parentID,objectName) values('327','326','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('328','326','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('329','326','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('330','326','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('331','326','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('332','326','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('333','255','Здание СУС')
insert into orderObjects (objectID,parentID,objectName) values('334','333','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('335','333','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('336','333','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('337','333','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('338','333','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('339','333','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('340','255','Здание АКЗ')
insert into orderObjects (objectID,parentID,objectName) values('341','340','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('342','340','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('343','340','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('344','340','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('345','340','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('346','340','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('347','255','Здание АСУ ТП')
insert into orderObjects (objectID,parentID,objectName) values('348','347','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('349','347','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('350','347','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('351','347','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('352','347','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('353','347','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('354','255','Здание для монтажа трансформаторов')
insert into orderObjects (objectID,parentID,objectName) values('355','354','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('356','354','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('357','354','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('358','354','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('359','354','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('360','354','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('361','255','Здание ОПУ-220кВ')
insert into orderObjects (objectID,parentID,objectName) values('362','361','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('363','361','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('364','361','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('365','361','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('366','361','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('367','361','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('368','255','Объект 30/35 №1')
insert into orderObjects (objectID,parentID,objectName) values('369','368','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('370','368','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('371','368','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('372','368','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('373','368','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('374','368','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('375','255','Объект 30/35 №2')
insert into orderObjects (objectID,parentID,objectName) values('376','375','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('377','375','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('378','375','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('379','375','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('380','375','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('381','375','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('382','255','Насосная пожаротушения РОДГ')
insert into orderObjects (objectID,parentID,objectName) values('383','382','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('384','382','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('385','382','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('386','382','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('387','382','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('388','382','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('389','255','Здание компрессорной 3КУ')
insert into orderObjects (objectID,parentID,objectName) values('390','389','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('391','389','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('392','389','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('393','389','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('394','389','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('395','389','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('396','255','Кузница/заготовительные мастерские')
insert into orderObjects (objectID,parentID,objectName) values('397','396','Система отопления')
insert into orderObjects (objectID,parentID,objectName) values('398','396','Система холодного водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('399','396','Система горячего водоснабжения')
insert into orderObjects (objectID,parentID,objectName) values('400','396','Система вентиляции')
insert into orderObjects (objectID,parentID,objectName) values('401','396','Система канализации')
insert into orderObjects (objectID,parentID,objectName) values('402','396','Система пожаротушения')
insert into orderObjects (objectID,parentID,objectName) values('403','255','КНС-1')
insert into orderObjects (objectID,parentID,objectName) values('404','403','Насос №1')
insert into orderObjects (objectID,parentID,objectName) values('405','403','Насос №2')
insert into orderObjects (objectID,parentID,objectName) values('406','403','Насос №3')
insert into orderObjects (objectID,parentID,objectName) values('407','255','КНС-2')
insert into orderObjects (objectID,parentID,objectName) values('408','407','Насос №1')
insert into orderObjects (objectID,parentID,objectName) values('409','407','Насос №2')
insert into orderObjects (objectID,parentID,objectName) values('410','407','Насос №3')
insert into orderObjects (objectID,parentID,objectName) values('411','0','Гидрогенераторы')
insert into orderObjects (objectID,parentID,objectName) values('412','411','ГА-1')
insert into orderObjects (objectID,parentID,objectName) values('413','412','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('414','413','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('415','413','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('416','413','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('417','413','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('418','413','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('419','412','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('420','419','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('421','419','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('422','419','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('423','412','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('424','423','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('425','412','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('426','425','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('427','425','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('428','412','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('429','428','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('430','428','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('431','428','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('432','412','Режим СК')
insert into orderObjects (objectID,parentID,objectName) values('433','411','ГА-2')
insert into orderObjects (objectID,parentID,objectName) values('434','433','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('435','434','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('436','434','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('437','434','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('438','434','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('439','434','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('440','433','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('441','440','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('442','440','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('443','440','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('444','433','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('445','444','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('446','433','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('447','446','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('448','446','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('449','433','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('450','449','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('451','449','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('452','449','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('453','433','Режим СК')
insert into orderObjects (objectID,parentID,objectName) values('454','411','ГА-3')
insert into orderObjects (objectID,parentID,objectName) values('455','454','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('456','455','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('457','455','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('458','455','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('459','455','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('460','455','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('461','454','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('462','461','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('463','461','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('464','461','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('465','454','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('466','465','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('467','454','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('468','467','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('469','467','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('470','454','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('471','470','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('472','470','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('473','470','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('474','411','ГА-4')
insert into orderObjects (objectID,parentID,objectName) values('475','474','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('476','475','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('477','475','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('478','475','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('479','475','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('480','475','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('481','474','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('482','481','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('483','481','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('484','481','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('485','474','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('486','485','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('487','474','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('488','487','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('489','487','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('490','474','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('491','490','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('492','490','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('493','490','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('494','411','ГА-5')
insert into orderObjects (objectID,parentID,objectName) values('495','494','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('496','495','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('497','495','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('498','495','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('499','495','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('500','495','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('501','494','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('502','501','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('503','501','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('504','501','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('505','494','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('506','505','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('507','494','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('508','507','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('509','507','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('510','494','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('511','510','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('512','510','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('513','510','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('514','411','ГА-6')
insert into orderObjects (objectID,parentID,objectName) values('515','514','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('516','515','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('517','515','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('518','515','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('519','515','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('520','515','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('521','514','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('522','521','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('523','521','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('524','521','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('525','514','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('526','525','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('527','514','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('528','527','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('529','527','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('530','514','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('531','530','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('532','530','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('533','530','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('534','411','ГА-7')
insert into orderObjects (objectID,parentID,objectName) values('535','534','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('536','535','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('537','535','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('538','535','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('539','535','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('540','535','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('541','534','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('542','541','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('543','541','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('544','541','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('545','534','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('546','545','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('547','534','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('548','547','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('549','547','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('550','534','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('551','550','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('552','550','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('553','550','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('554','411','ГА-8')
insert into orderObjects (objectID,parentID,objectName) values('555','554','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('556','555','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('557','555','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('558','555','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('559','555','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('560','555','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('561','554','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('562','561','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('563','561','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('564','561','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('565','554','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('566','565','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('567','554','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('568','567','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('569','567','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('570','554','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('571','570','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('572','570','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('573','570','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('574','411','ГА-9')
insert into orderObjects (objectID,parentID,objectName) values('575','574','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('576','575','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('577','575','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('578','575','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('579','575','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('580','575','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('581','574','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('582','581','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('583','581','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('584','581','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('585','574','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('586','585','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('587','574','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('588','587','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('589','587','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('590','574','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('591','590','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('592','590','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('593','590','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('594','574','Режим СК')
insert into orderObjects (objectID,parentID,objectName) values('595','411','ГА-10')
insert into orderObjects (objectID,parentID,objectName) values('596','595','Система регуллирования')
insert into orderObjects (objectID,parentID,objectName) values('597','596','МНУ-А')
insert into orderObjects (objectID,parentID,objectName) values('598','596','МНУ-Б')
insert into orderObjects (objectID,parentID,objectName) values('599','596','МНУ-В')
insert into orderObjects (objectID,parentID,objectName) values('600','596','МНУ-ВД')
insert into orderObjects (objectID,parentID,objectName) values('601','596','Лекажный насос')
insert into orderObjects (objectID,parentID,objectName) values('602','595','Система ТВС')
insert into orderObjects (objectID,parentID,objectName) values('603','602','Фильтр ТВС собственного водозабора')
insert into orderObjects (objectID,parentID,objectName) values('604','602','Фильтр ТВС с НБ')
insert into orderObjects (objectID,parentID,objectName) values('605','602','Фильтр ТВС с ВБ')
insert into orderObjects (objectID,parentID,objectName) values('606','595','Система охлаждения')
insert into orderObjects (objectID,parentID,objectName) values('607','606','Воздухоохладители')
insert into orderObjects (objectID,parentID,objectName) values('608','595','Система торможная')
insert into orderObjects (objectID,parentID,objectName) values('609','608','Колонка торможения')
insert into orderObjects (objectID,parentID,objectName) values('610','608','Тормозные домкраты')
insert into orderObjects (objectID,parentID,objectName) values('611','595','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('612','611','Дренажный насос А')
insert into orderObjects (objectID,parentID,objectName) values('613','611','Дренажный насос Б')
insert into orderObjects (objectID,parentID,objectName) values('614','611','Насос подъема ротора')
insert into orderObjects (objectID,parentID,objectName) values('615','595','Режим СК')
insert into orderObjects (objectID,parentID,objectName) values('616','0','Насосные')
insert into orderObjects (objectID,parentID,objectName) values('617','616','1ВС')
insert into orderObjects (objectID,parentID,objectName) values('618','617','Насос №1')
insert into orderObjects (objectID,parentID,objectName) values('619','617','Насос №2')
insert into orderObjects (objectID,parentID,objectName) values('620','617','Насос №4')
insert into orderObjects (objectID,parentID,objectName) values('621','617','Насос №3А')
insert into orderObjects (objectID,parentID,objectName) values('622','617','Насос №3Б')
insert into orderObjects (objectID,parentID,objectName) values('623','616','2ВС')
insert into orderObjects (objectID,parentID,objectName) values('624','623','Насос №1')
insert into orderObjects (objectID,parentID,objectName) values('625','623','Насос №2')
insert into orderObjects (objectID,parentID,objectName) values('626','623','Насос №3А')
insert into orderObjects (objectID,parentID,objectName) values('627','623','Насос №3Б')
insert into orderObjects (objectID,parentID,objectName) values('628','616','3ВС')
insert into orderObjects (objectID,parentID,objectName) values('629','628','Насос Д200/1')
insert into orderObjects (objectID,parentID,objectName) values('630','628','Насос Д200/2')
insert into orderObjects (objectID,parentID,objectName) values('631','628','Насос Н1')
insert into orderObjects (objectID,parentID,objectName) values('632','0','Пожаротушение')
insert into orderObjects (objectID,parentID,objectName) values('633','632','Насосы')
insert into orderObjects (objectID,parentID,objectName) values('634','633','ОПН-1')
insert into orderObjects (objectID,parentID,objectName) values('635','633','ОПН-2')
insert into orderObjects (objectID,parentID,objectName) values('636','633','ЖК-насос')
insert into orderObjects (objectID,parentID,objectName) values('637','633','БУНС')
insert into orderObjects (objectID,parentID,objectName) values('638','632','Кабельный коридор')
insert into orderObjects (objectID,parentID,objectName) values('639','638','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('640','638','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('641','638','3 Секция')
insert into orderObjects (objectID,parentID,objectName) values('642','638','4 Секция')
insert into orderObjects (objectID,parentID,objectName) values('643','638','5 Секция')
insert into orderObjects (objectID,parentID,objectName) values('644','638','БМП')
insert into orderObjects (objectID,parentID,objectName) values('645','638','Под ГЩУ')
insert into orderObjects (objectID,parentID,objectName) values('646','632','Кабельный туннель')
insert into orderObjects (objectID,parentID,objectName) values('647','646','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('648','646','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('649','646','3 Секция')
insert into orderObjects (objectID,parentID,objectName) values('650','646','4 Секция')
insert into orderObjects (objectID,parentID,objectName) values('651','646','5 Секция')
insert into orderObjects (objectID,parentID,objectName) values('652','632','Панель ПТ-1')
insert into orderObjects (objectID,parentID,objectName) values('653','632','Сигнализация')
insert into orderObjects (objectID,parentID,objectName) values('654','653','ППС-1')
insert into orderObjects (objectID,parentID,objectName) values('655','653','ППС-2')
insert into orderObjects (objectID,parentID,objectName) values('656','653','ППС-3')
insert into orderObjects (objectID,parentID,objectName) values('657','0','ГЩУ')
insert into orderObjects (objectID,parentID,objectName) values('658','0','Плотины')
insert into orderObjects (objectID,parentID,objectName) values('659','658','Земляная плотина №1')
insert into orderObjects (objectID,parentID,objectName) values('660','658','Земляная плотина №2')
insert into orderObjects (objectID,parentID,objectName) values('661','658','Земляная плотина №3')
insert into orderObjects (objectID,parentID,objectName) values('662','658','Земляная плотина №4')
insert into orderObjects (objectID,parentID,objectName) values('663','658','Водосливная плотина')
insert into orderObjects (objectID,parentID,objectName) values('664','663','Затворы')
insert into orderObjects (objectID,parentID,objectName) values('665','664','Затвор 1')
insert into orderObjects (objectID,parentID,objectName) values('666','664','Затвор 2')
insert into orderObjects (objectID,parentID,objectName) values('667','664','Затвор 3')
insert into orderObjects (objectID,parentID,objectName) values('668','664','Затвор 4')
insert into orderObjects (objectID,parentID,objectName) values('669','664','Затвор 5')
insert into orderObjects (objectID,parentID,objectName) values('670','664','Затвор 6')
insert into orderObjects (objectID,parentID,objectName) values('671','664','Затвор 7')
insert into orderObjects (objectID,parentID,objectName) values('672','664','Затвор 8')
insert into orderObjects (objectID,parentID,objectName) values('673','664','Ремонтный затвор 1')
insert into orderObjects (objectID,parentID,objectName) values('674','664','Ремонтный затвор 2')
insert into orderObjects (objectID,parentID,objectName) values('675','663','Пролеты')
insert into orderObjects (objectID,parentID,objectName) values('676','675','Пролет 1')
insert into orderObjects (objectID,parentID,objectName) values('677','675','Пролет 2')
insert into orderObjects (objectID,parentID,objectName) values('678','675','Пролет 3')
insert into orderObjects (objectID,parentID,objectName) values('679','675','Пролет 4')
insert into orderObjects (objectID,parentID,objectName) values('680','675','Пролет 5')
insert into orderObjects (objectID,parentID,objectName) values('681','675','Пролет 6')
insert into orderObjects (objectID,parentID,objectName) values('682','675','Пролет 7')
insert into orderObjects (objectID,parentID,objectName) values('683','675','Пролет 8')
insert into orderObjects (objectID,parentID,objectName) values('684','0','Компрессорные')
insert into orderObjects (objectID,parentID,objectName) values('685','684','1КУ')
insert into orderObjects (objectID,parentID,objectName) values('686','685','Компрессор 1')
insert into orderObjects (objectID,parentID,objectName) values('687','685','Компрессор 2')
insert into orderObjects (objectID,parentID,objectName) values('688','685','Компрессор 3')
insert into orderObjects (objectID,parentID,objectName) values('689','685','Компрессор 4')
insert into orderObjects (objectID,parentID,objectName) values('690','685','Компрессор 5')
insert into orderObjects (objectID,parentID,objectName) values('691','685','Компрессор 6')
insert into orderObjects (objectID,parentID,objectName) values('692','685','Компрессор 7')
insert into orderObjects (objectID,parentID,objectName) values('693','684','2КУ')
insert into orderObjects (objectID,parentID,objectName) values('694','693','Компрессор 1')
insert into orderObjects (objectID,parentID,objectName) values('695','693','Компрессор 2')
insert into orderObjects (objectID,parentID,objectName) values('696','693','Компрессор 3')
insert into orderObjects (objectID,parentID,objectName) values('697','693','Воздухосборник 1')
insert into orderObjects (objectID,parentID,objectName) values('698','693','Воздухосборник 2')
insert into orderObjects (objectID,parentID,objectName) values('699','693','Воздухосборник 3')
insert into orderObjects (objectID,parentID,objectName) values('700','693','Перепускной клапан 40*20 №1')
insert into orderObjects (objectID,parentID,objectName) values('701','693','Перепускной клапан 40*20 №2')
insert into orderObjects (objectID,parentID,objectName) values('702','693','Перепускной клапан 40*27 №1')
insert into orderObjects (objectID,parentID,objectName) values('703','693','Перепускной клапан 40*27 №2')
insert into orderObjects (objectID,parentID,objectName) values('704','684','3КУ')
insert into orderObjects (objectID,parentID,objectName) values('705','704','Компрессор 1')
insert into orderObjects (objectID,parentID,objectName) values('706','704','Компрессор 2')
insert into orderObjects (objectID,parentID,objectName) values('707','704','Компрессор 3')
insert into orderObjects (objectID,parentID,objectName) values('708','704','Компрессор 4')
insert into orderObjects (objectID,parentID,objectName) values('709','704','Компрессор 5')
insert into orderObjects (objectID,parentID,objectName) values('710','704','Воздухосборник 1')
insert into orderObjects (objectID,parentID,objectName) values('711','704','Воздухосборник 2')
insert into orderObjects (objectID,parentID,objectName) values('712','704','Воздухосборник 3')
insert into orderObjects (objectID,parentID,objectName) values('713','704','Воздухосборник 4')
insert into orderObjects (objectID,parentID,objectName) values('714','704','Воздухосборник 5')
insert into orderObjects (objectID,parentID,objectName) values('715','704','Перепускной клапан 40*20 №1')
insert into orderObjects (objectID,parentID,objectName) values('716','704','Перепускной клапан 40*20 №2')
insert into orderObjects (objectID,parentID,objectName) values('717','704','Перепускной клапан 40*20 №3')
insert into orderObjects (objectID,parentID,objectName) values('718','704','Перепускной клапан 40*20 №4')
insert into orderObjects (objectID,parentID,objectName) values('719','0','ВЛ')
insert into orderObjects (objectID,parentID,objectName) values('720','719','ВЛ 110кВ')
insert into orderObjects (objectID,parentID,objectName) values('721','720','КШТ-1')
insert into orderObjects (objectID,parentID,objectName) values('722','720','КШТ-2')
insert into orderObjects (objectID,parentID,objectName) values('723','720','ЧаТЭЦ')
insert into orderObjects (objectID,parentID,objectName) values('724','720','Каучук')
insert into orderObjects (objectID,parentID,objectName) values('725','720','Березовка')
insert into orderObjects (objectID,parentID,objectName) values('726','720','Дубовая')
insert into orderObjects (objectID,parentID,objectName) values('727','720','Водозабор-1')
insert into orderObjects (objectID,parentID,objectName) values('728','720','Водозабор-2')
insert into orderObjects (objectID,parentID,objectName) values('729','720','Светлая')
insert into orderObjects (objectID,parentID,objectName) values('730','720','Ивановка')
insert into orderObjects (objectID,parentID,objectName) values('731','719','ВЛ 220кВ')
insert into orderObjects (objectID,parentID,objectName) values('732','731','Иж-1')
insert into orderObjects (objectID,parentID,objectName) values('733','731','Иж-2')
insert into orderObjects (objectID,parentID,objectName) values('734','731','Каучук-1')
insert into orderObjects (objectID,parentID,objectName) values('735','731','Каучук-2')
insert into orderObjects (objectID,parentID,objectName) values('736','731','Светлая')
insert into orderObjects (objectID,parentID,objectName) values('737','719','ВЛ 500кВ')
insert into orderObjects (objectID,parentID,objectName) values('738','737','Емелино')
insert into orderObjects (objectID,parentID,objectName) values('739','738','РОДГ')
insert into orderObjects (objectID,parentID,objectName) values('740','737','Карманово')
insert into orderObjects (objectID,parentID,objectName) values('741','737','Вятка')


set identity_insert OrderObjects off