delete from orders
delete from OrderObjects 
set identity_insert OrderObjects on
insert into orderObjects (objectID,parentID,objectName) values('0','-1','ВотГЭС')
insert into orderObjects (objectID,parentID,objectName) values('1','0','Щиты СН')
insert into orderObjects (objectID,parentID,objectName) values('2','1','1Н')
insert into orderObjects (objectID,parentID,objectName) values('3','2','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('4','3','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('5','3','Сборка 136Н')
insert into orderObjects (objectID,parentID,objectName) values('6','3','Сборка 132Н')
insert into orderObjects (objectID,parentID,objectName) values('7','3','Сборка 132НА')
insert into orderObjects (objectID,parentID,objectName) values('8','3','Сборка 132НБ')
insert into orderObjects (objectID,parentID,objectName) values('9','3','Сборка 125Н')
insert into orderObjects (objectID,parentID,objectName) values('10','3','Сборка 1А (аварийное освещение)')
insert into orderObjects (objectID,parentID,objectName) values('11','3','Сборка 1Р (рабочее освещение)')
insert into orderObjects (objectID,parentID,objectName) values('12','3','Сборка 124Н')
insert into orderObjects (objectID,parentID,objectName) values('13','3','Сборка 1Н2')
insert into orderObjects (objectID,parentID,objectName) values('14','3','Сборка Р-1')
insert into orderObjects (objectID,parentID,objectName) values('15','3','Сборка Р-2')
insert into orderObjects (objectID,parentID,objectName) values('16','3','Сборка Р-3')
insert into orderObjects (objectID,parentID,objectName) values('17','3','Сборка Р-4')
insert into orderObjects (objectID,parentID,objectName) values('18','3','Сборка Р-5')
insert into orderObjects (objectID,parentID,objectName) values('19','3','Сборка Р-5А')
insert into orderObjects (objectID,parentID,objectName) values('20','3','Сборка Р-1А')
insert into orderObjects (objectID,parentID,objectName) values('21','2','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('22','2','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('23','22','Сборка 137Н')
insert into orderObjects (objectID,parentID,objectName) values('24','22','Сборка 1Н3')
insert into orderObjects (objectID,parentID,objectName) values('25','22','Сборка 122Н')
insert into orderObjects (objectID,parentID,objectName) values('26','22','Сборка 1Д (дежурное освещение)')
insert into orderObjects (objectID,parentID,objectName) values('27','22','Сборка 133Н')
insert into orderObjects (objectID,parentID,objectName) values('28','22','Сборка 134Н')
insert into orderObjects (objectID,parentID,objectName) values('29','22','Сборка  101Н')
insert into orderObjects (objectID,parentID,objectName) values('30','22','Сборка  101НА')
insert into orderObjects (objectID,parentID,objectName) values('31','22','Сборка  101НБ')
insert into orderObjects (objectID,parentID,objectName) values('32','22','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('33','1','2Н')
insert into orderObjects (objectID,parentID,objectName) values('34','33','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('35','33','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('36','35','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('37','35','Сборка 235Н')
insert into orderObjects (objectID,parentID,objectName) values('38','35','Сборка 239Н')
insert into orderObjects (objectID,parentID,objectName) values('39','35','Сборка 237Н')
insert into orderObjects (objectID,parentID,objectName) values('40','35','Сборка  Р-11')
insert into orderObjects (objectID,parentID,objectName) values('41','35','Сборка  Р-12')
insert into orderObjects (objectID,parentID,objectName) values('42','35','Сборка  Р-13')
insert into orderObjects (objectID,parentID,objectName) values('43','35','Сборка  Р-14')
insert into orderObjects (objectID,parentID,objectName) values('44','35','Сборка  Р-15')
insert into orderObjects (objectID,parentID,objectName) values('45','35','Сборка  Р-16')
insert into orderObjects (objectID,parentID,objectName) values('46','35','Сборка  Р-17')
insert into orderObjects (objectID,parentID,objectName) values('47','35','Сборка  Р-18')
insert into orderObjects (objectID,parentID,objectName) values('48','35','Сборка  Р-19')
insert into orderObjects (objectID,parentID,objectName) values('49','35','Сборка  Р-20')
insert into orderObjects (objectID,parentID,objectName) values('50','35','Сборка ПР01')
insert into orderObjects (objectID,parentID,objectName) values('51','35','Сборка Р-6')
insert into orderObjects (objectID,parentID,objectName) values('52','35','Сборка Р-7')
insert into orderObjects (objectID,parentID,objectName) values('53','35','Сборка Р-8')
insert into orderObjects (objectID,parentID,objectName) values('54','35','Сборка Р-9')
insert into orderObjects (objectID,parentID,objectName) values('55','35','Сборка Р-10')
insert into orderObjects (objectID,parentID,objectName) values('56','35','Сборка 2Р (рабочее освещение)')
insert into orderObjects (objectID,parentID,objectName) values('57','35','Сборка 2ШР5 (охранное освещение)')
insert into orderObjects (objectID,parentID,objectName) values('58','35','Сборка 1ШР6 (дежурное наружное освещение)')
insert into orderObjects (objectID,parentID,objectName) values('59','33','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('60','59','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('61','59','Сборка 223Н')
insert into orderObjects (objectID,parentID,objectName) values('62','59','Сборка 238Н')
insert into orderObjects (objectID,parentID,objectName) values('63','59','Сборка 236Н')
insert into orderObjects (objectID,parentID,objectName) values('64','59','Сборка 240Н')
insert into orderObjects (objectID,parentID,objectName) values('65','59','Сборка 2А (аварийное освещение)')
insert into orderObjects (objectID,parentID,objectName) values('66','59','Сборка 224Н')
insert into orderObjects (objectID,parentID,objectName) values('67','59','Сборка 5Н')
insert into orderObjects (objectID,parentID,objectName) values('68','59','Сборки 700')
insert into orderObjects (objectID,parentID,objectName) values('69','1','3Н')
insert into orderObjects (objectID,parentID,objectName) values('70','69','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('71','69','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('72','71','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('73','71','Панель №1')
insert into orderObjects (objectID,parentID,objectName) values('74','71','Панель №2')
insert into orderObjects (objectID,parentID,objectName) values('75','71','Панель №3')
insert into orderObjects (objectID,parentID,objectName) values('76','71','Панель №4')
insert into orderObjects (objectID,parentID,objectName) values('77','71','Сборка 323Н')
insert into orderObjects (objectID,parentID,objectName) values('78','71','Сборка 331Н')
insert into orderObjects (objectID,parentID,objectName) values('79','71','Сборка 327Н')
insert into orderObjects (objectID,parentID,objectName) values('80','71','Сборка 87НА')
insert into orderObjects (objectID,parentID,objectName) values('81','71','Сборка 87Н')
insert into orderObjects (objectID,parentID,objectName) values('82','71','Сборка КНС-1')
insert into orderObjects (objectID,parentID,objectName) values('83','71','Сборка 88НА')
insert into orderObjects (objectID,parentID,objectName) values('84','71','Сборка 324Н')
insert into orderObjects (objectID,parentID,objectName) values('85','69','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('86','85','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('87','85','Панель №7')
insert into orderObjects (objectID,parentID,objectName) values('88','85','Панель №8')
insert into orderObjects (objectID,parentID,objectName) values('89','85','Панель №9')
insert into orderObjects (objectID,parentID,objectName) values('90','85','Панель №10')
insert into orderObjects (objectID,parentID,objectName) values('91','85','Сборка 3ЩНО')
insert into orderObjects (objectID,parentID,objectName) values('92','85','Сборка 26Н')
insert into orderObjects (objectID,parentID,objectName) values('93','85','Сборка 332Н')
insert into orderObjects (objectID,parentID,objectName) values('94','85','Сборка 328Н')
insert into orderObjects (objectID,parentID,objectName) values('95','85','Сборка 326Н')
insert into orderObjects (objectID,parentID,objectName) values('96','85','Сборка 329Н')
insert into orderObjects (objectID,parentID,objectName) values('97','85','Сборка ГО-1')
insert into orderObjects (objectID,parentID,objectName) values('98','85','Сборка 143Н')
insert into orderObjects (objectID,parentID,objectName) values('99','85','Сборка 60Л')
insert into orderObjects (objectID,parentID,objectName) values('100','1','4Н')
insert into orderObjects (objectID,parentID,objectName) values('101','100','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('102','100','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('103','102','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('104','102','Сборка 426Н')
insert into orderObjects (objectID,parentID,objectName) values('105','100','2 Секция ')
insert into orderObjects (objectID,parentID,objectName) values('106','105','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('107','105','Сборка 425Н')
insert into orderObjects (objectID,parentID,objectName) values('108','105','Сборка 424НА')
insert into orderObjects (objectID,parentID,objectName) values('109','105','Сборка внутреннее освещение')
insert into orderObjects (objectID,parentID,objectName) values('110','105','Сборка наружное освещение')
insert into orderObjects (objectID,parentID,objectName) values('111','1','8Н')
insert into orderObjects (objectID,parentID,objectName) values('112','111','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('113','111','1 Секция ')
insert into orderObjects (objectID,parentID,objectName) values('114','113','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('115','113','Панель №1')
insert into orderObjects (objectID,parentID,objectName) values('116','113','Панель №2')
insert into orderObjects (objectID,parentID,objectName) values('117','113','Панель №3')
insert into orderObjects (objectID,parentID,objectName) values('118','113','Панель №4')
insert into orderObjects (objectID,parentID,objectName) values('119','113','Панель №5')
insert into orderObjects (objectID,parentID,objectName) values('120','113','Панель №6')
insert into orderObjects (objectID,parentID,objectName) values('121','113','Сборка 37НЗ')
insert into orderObjects (objectID,parentID,objectName) values('122','113','Сборка 37-07')
insert into orderObjects (objectID,parentID,objectName) values('123','113','Сборка 86Н')
insert into orderObjects (objectID,parentID,objectName) values('124','113','Сборка 1ШР2')
insert into orderObjects (objectID,parentID,objectName) values('125','113','Сборка 80Н')
insert into orderObjects (objectID,parentID,objectName) values('126','113','Сборка 85Н')
insert into orderObjects (objectID,parentID,objectName) values('127','113','Сборки 800Н')
insert into orderObjects (objectID,parentID,objectName) values('128','111','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('129','128','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('130','128','Сборка 37Н')
insert into orderObjects (objectID,parentID,objectName) values('131','128','Сборка 37-12')
insert into orderObjects (objectID,parentID,objectName) values('132','128','Сборка 37-13')
insert into orderObjects (objectID,parentID,objectName) values('133','128','Сборка 37-10')
insert into orderObjects (objectID,parentID,objectName) values('134','128','Сборка 3Н')
insert into orderObjects (objectID,parentID,objectName) values('135','128','Сборка 81Н')
insert into orderObjects (objectID,parentID,objectName) values('136','128','Сборка 82Н')
insert into orderObjects (objectID,parentID,objectName) values('137','128','Сборка 8ЩНО')
insert into orderObjects (objectID,parentID,objectName) values('138','128','Сборки 900Н')
insert into orderObjects (objectID,parentID,objectName) values('139','1','9Н')
insert into orderObjects (objectID,parentID,objectName) values('140','139','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('141','139','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('142','141','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('143','141','Сборка 91Н')
insert into orderObjects (objectID,parentID,objectName) values('144','141','Сборка 93Н')
insert into orderObjects (objectID,parentID,objectName) values('145','141','Сборка 96Н')
insert into orderObjects (objectID,parentID,objectName) values('146','141','Панель освещения')
insert into orderObjects (objectID,parentID,objectName) values('147','139','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('148','147','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('149','147','Сборка 92Н')
insert into orderObjects (objectID,parentID,objectName) values('150','147','Сборка 94Н')
insert into orderObjects (objectID,parentID,objectName) values('151','147','Сборка 95Н')
insert into orderObjects (objectID,parentID,objectName) values('152','1','90Н')
insert into orderObjects (objectID,parentID,objectName) values('153','152','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('154','152','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('155','154','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('156','152','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('157','156','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('158','156','Сбока 96Н')
insert into orderObjects (objectID,parentID,objectName) values('159','1','10Н')
insert into orderObjects (objectID,parentID,objectName) values('160','159','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('161','159','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('162','161','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('163','161','Панель №1')
insert into orderObjects (objectID,parentID,objectName) values('164','161','Панель №2')
insert into orderObjects (objectID,parentID,objectName) values('165','161','Панель №3')
insert into orderObjects (objectID,parentID,objectName) values('166','159','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('167','166','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('168','166','Панель №5')
insert into orderObjects (objectID,parentID,objectName) values('169','166','Панель №6')
insert into orderObjects (objectID,parentID,objectName) values('170','166','Панель №7')
insert into orderObjects (objectID,parentID,objectName) values('171','1','7Н')
insert into orderObjects (objectID,parentID,objectName) values('172','171','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('173','171','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('174','173','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('175','171','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('176','175','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('177','175','сбока 7Н2')
insert into orderObjects (objectID,parentID,objectName) values('178','1','35Н')
insert into orderObjects (objectID,parentID,objectName) values('179','178','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('180','179','Сборка 351Н')
insert into orderObjects (objectID,parentID,objectName) values('181','179','Сборка 353Н')
insert into orderObjects (objectID,parentID,objectName) values('182','179','Сборка 359Н')
insert into orderObjects (objectID,parentID,objectName) values('183','179','Сборка 357Н')
insert into orderObjects (objectID,parentID,objectName) values('184','179','Сборка 358Н')
insert into orderObjects (objectID,parentID,objectName) values('185','178','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('186','185','Сборка 352Н')
insert into orderObjects (objectID,parentID,objectName) values('187','185','Сборка 355Н')
insert into orderObjects (objectID,parentID,objectName) values('188','185','Сборка 356Н')
insert into orderObjects (objectID,parentID,objectName) values('189','185','Сборка 354Н')
insert into orderObjects (objectID,parentID,objectName) values('190','1','36Н')
insert into orderObjects (objectID,parentID,objectName) values('191','190','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('192','190','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('193','192','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('194','192','Сборка 367Н')
insert into orderObjects (objectID,parentID,objectName) values('195','190','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('196','195','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('197','195','Сборка 365Н')
insert into orderObjects (objectID,parentID,objectName) values('198','195','Сборка 368Н')
insert into orderObjects (objectID,parentID,objectName) values('199','195','Сборка КНС-2')
insert into orderObjects (objectID,parentID,objectName) values('200','195','Сборка 364Н')
insert into orderObjects (objectID,parentID,objectName) values('201','195','Сборка 361Н')
insert into orderObjects (objectID,parentID,objectName) values('202','195','Сборка 363Н')
insert into orderObjects (objectID,parentID,objectName) values('203','195','Сборка 362Н')
insert into orderObjects (objectID,parentID,objectName) values('204','195','Сборка 366Н')
insert into orderObjects (objectID,parentID,objectName) values('205','1','34Н')
insert into orderObjects (objectID,parentID,objectName) values('206','205','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('207','206','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('208','205','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('209','208','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('210','208','Сборка 71Н')
insert into orderObjects (objectID,parentID,objectName) values('211','208','ТП-1')
insert into orderObjects (objectID,parentID,objectName) values('212','208','Сборка DH1')
insert into orderObjects (objectID,parentID,objectName) values('213','208','Сборка DH2')
insert into orderObjects (objectID,parentID,objectName) values('214','208','ТП-2')
insert into orderObjects (objectID,parentID,objectName) values('215','208','Сборка DH3')
insert into orderObjects (objectID,parentID,objectName) values('216','208','Сборка DH4')
insert into orderObjects (objectID,parentID,objectName) values('217','208','Сборки 500Н')
insert into orderObjects (objectID,parentID,objectName) values('218','208','Сборки 600Н')
insert into orderObjects (objectID,parentID,objectName) values('219','208','6Н')
insert into orderObjects (objectID,parentID,objectName) values('220','0','СН генераторов')
insert into orderObjects (objectID,parentID,objectName) values('221','220','11Н')
insert into orderObjects (objectID,parentID,objectName) values('222','221','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('223','221','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('224','223','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('225','221','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('226','225','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('227','225','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('228','220','12Н')
insert into orderObjects (objectID,parentID,objectName) values('229','228','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('230','228','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('231','230','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('232','228','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('233','232','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('234','232','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('235','220','13Н')
insert into orderObjects (objectID,parentID,objectName) values('236','235','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('237','235','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('238','237','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('239','235','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('240','239','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('241','239','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('242','220','14Н')
insert into orderObjects (objectID,parentID,objectName) values('243','242','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('244','242','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('245','244','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('246','242','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('247','246','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('248','246','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('249','220','15Н')
insert into orderObjects (objectID,parentID,objectName) values('250','249','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('251','249','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('252','251','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('253','249','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('254','253','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('255','253','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('256','220','16Н')
insert into orderObjects (objectID,parentID,objectName) values('257','256','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('258','256','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('259','258','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('260','256','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('261','260','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('262','260','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('263','220','17Н')
insert into orderObjects (objectID,parentID,objectName) values('264','263','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('265','263','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('266','265','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('267','263','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('268','267','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('269','267','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('270','220','18Н')
insert into orderObjects (objectID,parentID,objectName) values('271','270','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('272','270','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('273','272','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('274','270','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('275','274','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('276','274','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('277','220','19Н')
insert into orderObjects (objectID,parentID,objectName) values('278','277','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('279','277','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('280','279','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('281','277','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('282','281','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('283','281','Секция 2-1')
insert into orderObjects (objectID,parentID,objectName) values('284','220','20Н')
insert into orderObjects (objectID,parentID,objectName) values('285','284','Секционный автомат')
insert into orderObjects (objectID,parentID,objectName) values('286','284','1 Секция')
insert into orderObjects (objectID,parentID,objectName) values('287','286','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('288','284','2 Секция')
insert into orderObjects (objectID,parentID,objectName) values('289','288','Вводной автомат')
insert into orderObjects (objectID,parentID,objectName) values('290','288','Секция 2-1')
set identity_insert OrderObjects off