delete from orders
delete from users
insert into users values('CORP\gschu','ГЩУ ВотГЭС','gschu@votges.rushydro.ru',1,0,0,0,0,0,0,0,0,0)
insert into users values('CORP\ChekunovaMV','Чекунова М.В.','ChekunovaMV@votges.rushydro.ru',1,1,1,1,1,1,1,1,1,1)
insert into users values('CORP\ByakovAG','Бяков А.Г.','ByakovAG@votges.rushydro.ru',0,0,0,0,0,1,0,0,0,0)
insert into users values('CORP\DeevAP','Деев А.П.','DeevAP@votges.rushydro.ru',0,0,0,0,0,1,0,0,0,0)
insert into users values('CORP\AlekseevVG','Алексеев В.Г.','AlekseevVG@votges.rushydro.ru',0,1,0,0,0,1,0,0,0,1)
insert into users values('CORP\VotintsevAN','Вотинцев А.Н.','VotintsevAN@votges.rushydro.ru',0,1,0,0,0,1,0,0,0,1)
insert into users values('CORP\BalabanovVV','Балабанов В.В.','BalabanovVV@votges.rushydro.ru',1,1,1,1,1,1,1,1,1,1)
insert into users values('CORP\TsirlinSL','Цирлин С.Л.','TsirlinSL@votges.rushydro.ru',0,1,1,1,1,0,1,0,0,1)
insert into users values('CORP\AlekseevVV','Алексеев В.В.','AlekseevVV@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\LukinSV','Лукин С.В.','LukinSV@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\BorisevichVI','Борисевич В.И.','BorisevichVI@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\SalnikovSM','Сальников С.М.','SalnikovSM@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\ChirkaRI','Чирка Р.И.','ChirkaRI@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\IvanovAV','Иванов А.В.','IvanovAV@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\PolyaninAV','Полянин А.В.','PolyaninAV@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\RusskihAI','Русских А.И.','RusskihAI@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\GunchenkoAA','Гунченко А.А.','GunchenkoAA@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\MihaylovVV','Михайлов В.В.','MihaylovVV@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\BurnyshevKN','Бурнышев К.Н.','BurnyshevKN@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\TrefilovAV','Трефилов А.В.','TrefilovAV@votges.rushydro.ru',0,1,1,1,1,1,1,0,0,0)
insert into users values('CORP\KetovaLZ','Кетова Л.З.','KetovaLZ@votges.rushydro.ru',0,0,1,1,1,1,1,0,0,0)
insert into users values('CORP\FisenkoSV','Фисенко С.В.','FisenkoSV@votges.rushydro.ru',0,0,1,1,1,1,1,0,0,0)
insert into users values('CORP\KirienkoDM','Кириенко Д.М.','KirienkoDM@votges.rushydro.ru',0,0,1,1,1,1,1,0,0,0)
insert into users values('CORP\SentyabovAA','Сентябов А.А.','SentyabovAA@votges.rushydro.ru',0,0,1,1,1,1,1,0,0,0)
insert into users values('CORP\SalnikovES','Сальников Е.С.','SalnikovES@votges.rushydro.ru',0,0,1,1,1,1,1,0,0,0)
insert into users values('CORP\KocheevNN','Кочеев Н.Н.','KocheevNN@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\LazarevAI','Лазарев А.И.','LazarevAI@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\KuznetsovAI','Кузнецов А.И.','KuznetsovAI@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\ZykovSL','Зыков С.Л.','ZykovSL@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\NikonovAA','Никонов А.А.','NikonovAA@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\ByakovaTA','Бякова Т.А.','ByakovaTA@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\ChernyshevAA','Чернышов А.Я.','ChernyshevAA@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\SidorovVL','Сидоров В.Л.','SidorovVL@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\ShamsuarovRA','Шамсуаров Р.А.','ShamsuarovRA@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\VasilkovVS','Васильков В.С.','VasilkovVS@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\BahinVV','Бахин В.В.','BahinVV@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('CORP\ShupletsovKG','Шуплецов К.Г.','ShupletsovKG@votges.rushydro.ru',0,1,1,1,1,0,0,0,0,1)
insert into users values('\','Турборемонт','KurbatovVP@votges.rushydro.ru',0,1,0,0,0,0,0,0,0,1)
insert into users values('\','Электроремонт','ToschevikovVM@votges.rushydro.ru',0,1,0,0,0,0,0,0,0,1)
insert into users values('\','Гидроремонт','KuzminyhIB@hvkk.rushydro.ru',0,1,0,0,0,0,0,0,0,1)
insert into users values('\','Шлюз','',0,1,0,0,0,0,0,0,0,1)
insert into users values('\','Водоканал','',0,1,0,0,0,0,0,0,0,1)
insert into users values('\','Вега-сервис','IvanovaNV@votges.rushydro.ru',0,1,0,0,0,0,0,0,0,1)
