//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_OrderObjects", "OrderObjects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VotGESOrders.Web.ADONETEntities.OrderObjects), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersAccept", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersBan", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersCancel", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersClose", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersComplete", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersCreate", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]
[assembly: EdmRelationshipAttribute("VotGESOrdersModel", "FK_Orders_UsersOpen", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VotGESOrders.Web.ADONETEntities.Users), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VotGESOrders.Web.ADONETEntities.Orders), true)]

#endregion

namespace VotGESOrders.Web.ADONETEntities
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class VotGESOrdersEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект VotGESOrdersEntities, используя строку соединения из раздела "VotGESOrdersEntities" файла конфигурации приложения.
        /// </summary>
        public VotGESOrdersEntities() : base("name=VotGESOrdersEntities", "VotGESOrdersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта VotGESOrdersEntities.
        /// </summary>
        public VotGESOrdersEntities(string connectionString) : base(connectionString, "VotGESOrdersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта VotGESOrdersEntities.
        /// </summary>
        public VotGESOrdersEntities(EntityConnection connection) : base(connection, "VotGESOrdersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<OrderObjects> OrderObjects
        {
            get
            {
                if ((_OrderObjects == null))
                {
                    _OrderObjects = base.CreateObjectSet<OrderObjects>("OrderObjects");
                }
                return _OrderObjects;
            }
        }
        private ObjectSet<OrderObjects> _OrderObjects;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Orders> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Orders>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Orders> _Orders;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet OrderObjects. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToOrderObjects(OrderObjects orderObjects)
        {
            base.AddObject("OrderObjects", orderObjects);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Orders. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToOrders(Orders orders)
        {
            base.AddObject("Orders", orders);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Users. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VotGESOrdersModel", Name="OrderObjects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderObjects : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта OrderObjects.
        /// </summary>
        /// <param name="objectID">Исходное значение свойства objectID.</param>
        /// <param name="parentID">Исходное значение свойства parentID.</param>
        /// <param name="objectName">Исходное значение свойства objectName.</param>
        public static OrderObjects CreateOrderObjects(global::System.Int32 objectID, global::System.Int32 parentID, global::System.String objectName)
        {
            OrderObjects orderObjects = new OrderObjects();
            orderObjects.objectID = objectID;
            orderObjects.parentID = parentID;
            orderObjects.objectName = objectName;
            return orderObjects;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 objectID
        {
            get
            {
                return _objectID;
            }
            set
            {
                if (_objectID != value)
                {
                    OnobjectIDChanging(value);
                    ReportPropertyChanging("objectID");
                    _objectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("objectID");
                    OnobjectIDChanged();
                }
            }
        }
        private global::System.Int32 _objectID;
        partial void OnobjectIDChanging(global::System.Int32 value);
        partial void OnobjectIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentID
        {
            get
            {
                return _parentID;
            }
            set
            {
                OnparentIDChanging(value);
                ReportPropertyChanging("parentID");
                _parentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentID");
                OnparentIDChanged();
            }
        }
        private global::System.Int32 _parentID;
        partial void OnparentIDChanging(global::System.Int32 value);
        partial void OnparentIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String objectName
        {
            get
            {
                return _objectName;
            }
            set
            {
                OnobjectNameChanging(value);
                ReportPropertyChanging("objectName");
                _objectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("objectName");
                OnobjectNameChanged();
            }
        }
        private global::System.String _objectName;
        partial void OnobjectNameChanging(global::System.String value);
        partial void OnobjectNameChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_OrderObjects", "Orders")]
        public EntityCollection<Orders> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_OrderObjects", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_OrderObjects", "Orders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VotGESOrdersModel", Name="Orders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Orders : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Orders.
        /// </summary>
        /// <param name="orderNumber">Исходное значение свойства orderNumber.</param>
        /// <param name="userCreateOrderID">Исходное значение свойства userCreateOrderID.</param>
        /// <param name="orderDateCreate">Исходное значение свойства orderDateCreate.</param>
        /// <param name="orderLastUpdate">Исходное значение свойства orderLastUpdate.</param>
        /// <param name="planStartDate">Исходное значение свойства planStartDate.</param>
        /// <param name="planStopDate">Исходное значение свойства planStopDate.</param>
        /// <param name="orderText">Исходное значение свойства orderText.</param>
        /// <param name="orderType">Исходное значение свойства orderType.</param>
        /// <param name="agreeText">Исходное значение свойства agreeText.</param>
        /// <param name="agreeUsersIDS">Исходное значение свойства agreeUsersIDS.</param>
        /// <param name="readyTime">Исходное значение свойства readyTime.</param>
        /// <param name="orderObjectID">Исходное значение свойства orderObjectID.</param>
        /// <param name="orderObjectAddInfo">Исходное значение свойства orderObjectAddInfo.</param>
        /// <param name="orderCreated">Исходное значение свойства orderCreated.</param>
        /// <param name="orderAccepted">Исходное значение свойства orderAccepted.</param>
        /// <param name="orderBanned">Исходное значение свойства orderBanned.</param>
        /// <param name="orderOpened">Исходное значение свойства orderOpened.</param>
        /// <param name="orderClosed">Исходное значение свойства orderClosed.</param>
        /// <param name="orderCanceled">Исходное значение свойства orderCanceled.</param>
        /// <param name="orderCompleted">Исходное значение свойства orderCompleted.</param>
        /// <param name="orderExtended">Исходное значение свойства orderExtended.</param>
        /// <param name="orderAskExtended">Исходное значение свойства orderAskExtended.</param>
        /// <param name="orderIsExtend">Исходное значение свойства orderIsExtend.</param>
        /// <param name="orderState">Исходное значение свойства orderState.</param>
        public static Orders CreateOrders(global::System.Int32 orderNumber, global::System.Int32 userCreateOrderID, global::System.DateTime orderDateCreate, global::System.DateTime orderLastUpdate, global::System.DateTime planStartDate, global::System.DateTime planStopDate, global::System.String orderText, global::System.String orderType, global::System.String agreeText, global::System.String agreeUsersIDS, global::System.String readyTime, global::System.Int32 orderObjectID, global::System.String orderObjectAddInfo, global::System.Boolean orderCreated, global::System.Boolean orderAccepted, global::System.Boolean orderBanned, global::System.Boolean orderOpened, global::System.Boolean orderClosed, global::System.Boolean orderCanceled, global::System.Boolean orderCompleted, global::System.Boolean orderExtended, global::System.Boolean orderAskExtended, global::System.Boolean orderIsExtend, global::System.String orderState)
        {
            Orders orders = new Orders();
            orders.orderNumber = orderNumber;
            orders.userCreateOrderID = userCreateOrderID;
            orders.orderDateCreate = orderDateCreate;
            orders.orderLastUpdate = orderLastUpdate;
            orders.planStartDate = planStartDate;
            orders.planStopDate = planStopDate;
            orders.orderText = orderText;
            orders.orderType = orderType;
            orders.agreeText = agreeText;
            orders.agreeUsersIDS = agreeUsersIDS;
            orders.readyTime = readyTime;
            orders.orderObjectID = orderObjectID;
            orders.orderObjectAddInfo = orderObjectAddInfo;
            orders.orderCreated = orderCreated;
            orders.orderAccepted = orderAccepted;
            orders.orderBanned = orderBanned;
            orders.orderOpened = orderOpened;
            orders.orderClosed = orderClosed;
            orders.orderCanceled = orderCanceled;
            orders.orderCompleted = orderCompleted;
            orders.orderExtended = orderExtended;
            orders.orderAskExtended = orderAskExtended;
            orders.orderIsExtend = orderIsExtend;
            orders.orderState = orderState;
            return orders;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parentOrderNumber
        {
            get
            {
                return _parentOrderNumber;
            }
            set
            {
                OnparentOrderNumberChanging(value);
                ReportPropertyChanging("parentOrderNumber");
                _parentOrderNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentOrderNumber");
                OnparentOrderNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _parentOrderNumber;
        partial void OnparentOrderNumberChanging(Nullable<global::System.Int32> value);
        partial void OnparentOrderNumberChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> childOrderNumber
        {
            get
            {
                return _childOrderNumber;
            }
            set
            {
                OnchildOrderNumberChanging(value);
                ReportPropertyChanging("childOrderNumber");
                _childOrderNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("childOrderNumber");
                OnchildOrderNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _childOrderNumber;
        partial void OnchildOrderNumberChanging(Nullable<global::System.Int32> value);
        partial void OnchildOrderNumberChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderNumber
        {
            get
            {
                return _orderNumber;
            }
            set
            {
                if (_orderNumber != value)
                {
                    OnorderNumberChanging(value);
                    ReportPropertyChanging("orderNumber");
                    _orderNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("orderNumber");
                    OnorderNumberChanged();
                }
            }
        }
        private global::System.Int32 _orderNumber;
        partial void OnorderNumberChanging(global::System.Int32 value);
        partial void OnorderNumberChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userCreateOrderID
        {
            get
            {
                return _userCreateOrderID;
            }
            set
            {
                OnuserCreateOrderIDChanging(value);
                ReportPropertyChanging("userCreateOrderID");
                _userCreateOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userCreateOrderID");
                OnuserCreateOrderIDChanged();
            }
        }
        private global::System.Int32 _userCreateOrderID;
        partial void OnuserCreateOrderIDChanging(global::System.Int32 value);
        partial void OnuserCreateOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userAcceptOrderID
        {
            get
            {
                return _userAcceptOrderID;
            }
            set
            {
                OnuserAcceptOrderIDChanging(value);
                ReportPropertyChanging("userAcceptOrderID");
                _userAcceptOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userAcceptOrderID");
                OnuserAcceptOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userAcceptOrderID;
        partial void OnuserAcceptOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserAcceptOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userBanOrderID
        {
            get
            {
                return _userBanOrderID;
            }
            set
            {
                OnuserBanOrderIDChanging(value);
                ReportPropertyChanging("userBanOrderID");
                _userBanOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userBanOrderID");
                OnuserBanOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userBanOrderID;
        partial void OnuserBanOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserBanOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userCloseOrderID
        {
            get
            {
                return _userCloseOrderID;
            }
            set
            {
                OnuserCloseOrderIDChanging(value);
                ReportPropertyChanging("userCloseOrderID");
                _userCloseOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userCloseOrderID");
                OnuserCloseOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userCloseOrderID;
        partial void OnuserCloseOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserCloseOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userCompleteOrderID
        {
            get
            {
                return _userCompleteOrderID;
            }
            set
            {
                OnuserCompleteOrderIDChanging(value);
                ReportPropertyChanging("userCompleteOrderID");
                _userCompleteOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userCompleteOrderID");
                OnuserCompleteOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userCompleteOrderID;
        partial void OnuserCompleteOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserCompleteOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userOpenOrderID
        {
            get
            {
                return _userOpenOrderID;
            }
            set
            {
                OnuserOpenOrderIDChanging(value);
                ReportPropertyChanging("userOpenOrderID");
                _userOpenOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userOpenOrderID");
                OnuserOpenOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userOpenOrderID;
        partial void OnuserOpenOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserOpenOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> userCancelOrderID
        {
            get
            {
                return _userCancelOrderID;
            }
            set
            {
                OnuserCancelOrderIDChanging(value);
                ReportPropertyChanging("userCancelOrderID");
                _userCancelOrderID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userCancelOrderID");
                OnuserCancelOrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _userCancelOrderID;
        partial void OnuserCancelOrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnuserCancelOrderIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime orderDateCreate
        {
            get
            {
                return _orderDateCreate;
            }
            set
            {
                OnorderDateCreateChanging(value);
                ReportPropertyChanging("orderDateCreate");
                _orderDateCreate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateCreate");
                OnorderDateCreateChanged();
            }
        }
        private global::System.DateTime _orderDateCreate;
        partial void OnorderDateCreateChanging(global::System.DateTime value);
        partial void OnorderDateCreateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderDateAccept
        {
            get
            {
                return _orderDateAccept;
            }
            set
            {
                OnorderDateAcceptChanging(value);
                ReportPropertyChanging("orderDateAccept");
                _orderDateAccept = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateAccept");
                OnorderDateAcceptChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderDateAccept;
        partial void OnorderDateAcceptChanging(Nullable<global::System.DateTime> value);
        partial void OnorderDateAcceptChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderDateBan
        {
            get
            {
                return _orderDateBan;
            }
            set
            {
                OnorderDateBanChanging(value);
                ReportPropertyChanging("orderDateBan");
                _orderDateBan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateBan");
                OnorderDateBanChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderDateBan;
        partial void OnorderDateBanChanging(Nullable<global::System.DateTime> value);
        partial void OnorderDateBanChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderDateClose
        {
            get
            {
                return _orderDateClose;
            }
            set
            {
                OnorderDateCloseChanging(value);
                ReportPropertyChanging("orderDateClose");
                _orderDateClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateClose");
                OnorderDateCloseChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderDateClose;
        partial void OnorderDateCloseChanging(Nullable<global::System.DateTime> value);
        partial void OnorderDateCloseChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderDateOpen
        {
            get
            {
                return _orderDateOpen;
            }
            set
            {
                OnorderDateOpenChanging(value);
                ReportPropertyChanging("orderDateOpen");
                _orderDateOpen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateOpen");
                OnorderDateOpenChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderDateOpen;
        partial void OnorderDateOpenChanging(Nullable<global::System.DateTime> value);
        partial void OnorderDateOpenChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderDateComplete
        {
            get
            {
                return _orderDateComplete;
            }
            set
            {
                OnorderDateCompleteChanging(value);
                ReportPropertyChanging("orderDateComplete");
                _orderDateComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateComplete");
                OnorderDateCompleteChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderDateComplete;
        partial void OnorderDateCompleteChanging(Nullable<global::System.DateTime> value);
        partial void OnorderDateCompleteChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderDateCancel
        {
            get
            {
                return _orderDateCancel;
            }
            set
            {
                OnorderDateCancelChanging(value);
                ReportPropertyChanging("orderDateCancel");
                _orderDateCancel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderDateCancel");
                OnorderDateCancelChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderDateCancel;
        partial void OnorderDateCancelChanging(Nullable<global::System.DateTime> value);
        partial void OnorderDateCancelChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime orderLastUpdate
        {
            get
            {
                return _orderLastUpdate;
            }
            set
            {
                OnorderLastUpdateChanging(value);
                ReportPropertyChanging("orderLastUpdate");
                _orderLastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderLastUpdate");
                OnorderLastUpdateChanged();
            }
        }
        private global::System.DateTime _orderLastUpdate;
        partial void OnorderLastUpdateChanging(global::System.DateTime value);
        partial void OnorderLastUpdateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acceptText
        {
            get
            {
                return _acceptText;
            }
            set
            {
                OnacceptTextChanging(value);
                ReportPropertyChanging("acceptText");
                _acceptText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acceptText");
                OnacceptTextChanged();
            }
        }
        private global::System.String _acceptText;
        partial void OnacceptTextChanging(global::System.String value);
        partial void OnacceptTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String banText
        {
            get
            {
                return _banText;
            }
            set
            {
                OnbanTextChanging(value);
                ReportPropertyChanging("banText");
                _banText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("banText");
                OnbanTextChanged();
            }
        }
        private global::System.String _banText;
        partial void OnbanTextChanging(global::System.String value);
        partial void OnbanTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String openText
        {
            get
            {
                return _openText;
            }
            set
            {
                OnopenTextChanging(value);
                ReportPropertyChanging("openText");
                _openText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("openText");
                OnopenTextChanged();
            }
        }
        private global::System.String _openText;
        partial void OnopenTextChanging(global::System.String value);
        partial void OnopenTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String closeText
        {
            get
            {
                return _closeText;
            }
            set
            {
                OncloseTextChanging(value);
                ReportPropertyChanging("closeText");
                _closeText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("closeText");
                OncloseTextChanged();
            }
        }
        private global::System.String _closeText;
        partial void OncloseTextChanging(global::System.String value);
        partial void OncloseTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String completeText
        {
            get
            {
                return _completeText;
            }
            set
            {
                OncompleteTextChanging(value);
                ReportPropertyChanging("completeText");
                _completeText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("completeText");
                OncompleteTextChanged();
            }
        }
        private global::System.String _completeText;
        partial void OncompleteTextChanging(global::System.String value);
        partial void OncompleteTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cancelText
        {
            get
            {
                return _cancelText;
            }
            set
            {
                OncancelTextChanging(value);
                ReportPropertyChanging("cancelText");
                _cancelText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cancelText");
                OncancelTextChanged();
            }
        }
        private global::System.String _cancelText;
        partial void OncancelTextChanging(global::System.String value);
        partial void OncancelTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createText
        {
            get
            {
                return _createText;
            }
            set
            {
                OncreateTextChanging(value);
                ReportPropertyChanging("createText");
                _createText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createText");
                OncreateTextChanged();
            }
        }
        private global::System.String _createText;
        partial void OncreateTextChanging(global::System.String value);
        partial void OncreateTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime planStartDate
        {
            get
            {
                return _planStartDate;
            }
            set
            {
                OnplanStartDateChanging(value);
                ReportPropertyChanging("planStartDate");
                _planStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("planStartDate");
                OnplanStartDateChanged();
            }
        }
        private global::System.DateTime _planStartDate;
        partial void OnplanStartDateChanging(global::System.DateTime value);
        partial void OnplanStartDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime planStopDate
        {
            get
            {
                return _planStopDate;
            }
            set
            {
                OnplanStopDateChanging(value);
                ReportPropertyChanging("planStopDate");
                _planStopDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("planStopDate");
                OnplanStopDateChanged();
            }
        }
        private global::System.DateTime _planStopDate;
        partial void OnplanStopDateChanging(global::System.DateTime value);
        partial void OnplanStopDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> faktStartDate
        {
            get
            {
                return _faktStartDate;
            }
            set
            {
                OnfaktStartDateChanging(value);
                ReportPropertyChanging("faktStartDate");
                _faktStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("faktStartDate");
                OnfaktStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _faktStartDate;
        partial void OnfaktStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnfaktStartDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> faktStopDate
        {
            get
            {
                return _faktStopDate;
            }
            set
            {
                OnfaktStopDateChanging(value);
                ReportPropertyChanging("faktStopDate");
                _faktStopDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("faktStopDate");
                OnfaktStopDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _faktStopDate;
        partial void OnfaktStopDateChanging(Nullable<global::System.DateTime> value);
        partial void OnfaktStopDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> faktCompleteDate
        {
            get
            {
                return _faktCompleteDate;
            }
            set
            {
                OnfaktCompleteDateChanging(value);
                ReportPropertyChanging("faktCompleteDate");
                _faktCompleteDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("faktCompleteDate");
                OnfaktCompleteDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _faktCompleteDate;
        partial void OnfaktCompleteDateChanging(Nullable<global::System.DateTime> value);
        partial void OnfaktCompleteDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String orderText
        {
            get
            {
                return _orderText;
            }
            set
            {
                OnorderTextChanging(value);
                ReportPropertyChanging("orderText");
                _orderText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("orderText");
                OnorderTextChanged();
            }
        }
        private global::System.String _orderText;
        partial void OnorderTextChanging(global::System.String value);
        partial void OnorderTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String orderType
        {
            get
            {
                return _orderType;
            }
            set
            {
                OnorderTypeChanging(value);
                ReportPropertyChanging("orderType");
                _orderType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("orderType");
                OnorderTypeChanged();
            }
        }
        private global::System.String _orderType;
        partial void OnorderTypeChanging(global::System.String value);
        partial void OnorderTypeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String agreeText
        {
            get
            {
                return _agreeText;
            }
            set
            {
                OnagreeTextChanging(value);
                ReportPropertyChanging("agreeText");
                _agreeText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("agreeText");
                OnagreeTextChanged();
            }
        }
        private global::System.String _agreeText;
        partial void OnagreeTextChanging(global::System.String value);
        partial void OnagreeTextChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String agreeUsersIDS
        {
            get
            {
                return _agreeUsersIDS;
            }
            set
            {
                OnagreeUsersIDSChanging(value);
                ReportPropertyChanging("agreeUsersIDS");
                _agreeUsersIDS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("agreeUsersIDS");
                OnagreeUsersIDSChanged();
            }
        }
        private global::System.String _agreeUsersIDS;
        partial void OnagreeUsersIDSChanging(global::System.String value);
        partial void OnagreeUsersIDSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String readyTime
        {
            get
            {
                return _readyTime;
            }
            set
            {
                OnreadyTimeChanging(value);
                ReportPropertyChanging("readyTime");
                _readyTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("readyTime");
                OnreadyTimeChanged();
            }
        }
        private global::System.String _readyTime;
        partial void OnreadyTimeChanging(global::System.String value);
        partial void OnreadyTimeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderObjectID
        {
            get
            {
                return _orderObjectID;
            }
            set
            {
                OnorderObjectIDChanging(value);
                ReportPropertyChanging("orderObjectID");
                _orderObjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderObjectID");
                OnorderObjectIDChanged();
            }
        }
        private global::System.Int32 _orderObjectID;
        partial void OnorderObjectIDChanging(global::System.Int32 value);
        partial void OnorderObjectIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String orderObjectAddInfo
        {
            get
            {
                return _orderObjectAddInfo;
            }
            set
            {
                OnorderObjectAddInfoChanging(value);
                ReportPropertyChanging("orderObjectAddInfo");
                _orderObjectAddInfo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("orderObjectAddInfo");
                OnorderObjectAddInfoChanged();
            }
        }
        private global::System.String _orderObjectAddInfo;
        partial void OnorderObjectAddInfoChanging(global::System.String value);
        partial void OnorderObjectAddInfoChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderCreated
        {
            get
            {
                return _orderCreated;
            }
            set
            {
                OnorderCreatedChanging(value);
                ReportPropertyChanging("orderCreated");
                _orderCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderCreated");
                OnorderCreatedChanged();
            }
        }
        private global::System.Boolean _orderCreated;
        partial void OnorderCreatedChanging(global::System.Boolean value);
        partial void OnorderCreatedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderAccepted
        {
            get
            {
                return _orderAccepted;
            }
            set
            {
                OnorderAcceptedChanging(value);
                ReportPropertyChanging("orderAccepted");
                _orderAccepted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderAccepted");
                OnorderAcceptedChanged();
            }
        }
        private global::System.Boolean _orderAccepted;
        partial void OnorderAcceptedChanging(global::System.Boolean value);
        partial void OnorderAcceptedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderBanned
        {
            get
            {
                return _orderBanned;
            }
            set
            {
                OnorderBannedChanging(value);
                ReportPropertyChanging("orderBanned");
                _orderBanned = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderBanned");
                OnorderBannedChanged();
            }
        }
        private global::System.Boolean _orderBanned;
        partial void OnorderBannedChanging(global::System.Boolean value);
        partial void OnorderBannedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderOpened
        {
            get
            {
                return _orderOpened;
            }
            set
            {
                OnorderOpenedChanging(value);
                ReportPropertyChanging("orderOpened");
                _orderOpened = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderOpened");
                OnorderOpenedChanged();
            }
        }
        private global::System.Boolean _orderOpened;
        partial void OnorderOpenedChanging(global::System.Boolean value);
        partial void OnorderOpenedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderClosed
        {
            get
            {
                return _orderClosed;
            }
            set
            {
                OnorderClosedChanging(value);
                ReportPropertyChanging("orderClosed");
                _orderClosed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderClosed");
                OnorderClosedChanged();
            }
        }
        private global::System.Boolean _orderClosed;
        partial void OnorderClosedChanging(global::System.Boolean value);
        partial void OnorderClosedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderCanceled
        {
            get
            {
                return _orderCanceled;
            }
            set
            {
                OnorderCanceledChanging(value);
                ReportPropertyChanging("orderCanceled");
                _orderCanceled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderCanceled");
                OnorderCanceledChanged();
            }
        }
        private global::System.Boolean _orderCanceled;
        partial void OnorderCanceledChanging(global::System.Boolean value);
        partial void OnorderCanceledChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderCompleted
        {
            get
            {
                return _orderCompleted;
            }
            set
            {
                OnorderCompletedChanging(value);
                ReportPropertyChanging("orderCompleted");
                _orderCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderCompleted");
                OnorderCompletedChanged();
            }
        }
        private global::System.Boolean _orderCompleted;
        partial void OnorderCompletedChanging(global::System.Boolean value);
        partial void OnorderCompletedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderExtended
        {
            get
            {
                return _orderExtended;
            }
            set
            {
                OnorderExtendedChanging(value);
                ReportPropertyChanging("orderExtended");
                _orderExtended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderExtended");
                OnorderExtendedChanged();
            }
        }
        private global::System.Boolean _orderExtended;
        partial void OnorderExtendedChanging(global::System.Boolean value);
        partial void OnorderExtendedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderAskExtended
        {
            get
            {
                return _orderAskExtended;
            }
            set
            {
                OnorderAskExtendedChanging(value);
                ReportPropertyChanging("orderAskExtended");
                _orderAskExtended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderAskExtended");
                OnorderAskExtendedChanged();
            }
        }
        private global::System.Boolean _orderAskExtended;
        partial void OnorderAskExtendedChanging(global::System.Boolean value);
        partial void OnorderAskExtendedChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean orderIsExtend
        {
            get
            {
                return _orderIsExtend;
            }
            set
            {
                OnorderIsExtendChanging(value);
                ReportPropertyChanging("orderIsExtend");
                _orderIsExtend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderIsExtend");
                OnorderIsExtendChanged();
            }
        }
        private global::System.Boolean _orderIsExtend;
        partial void OnorderIsExtendChanging(global::System.Boolean value);
        partial void OnorderIsExtendChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String orderState
        {
            get
            {
                return _orderState;
            }
            set
            {
                OnorderStateChanging(value);
                ReportPropertyChanging("orderState");
                _orderState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("orderState");
                OnorderStateChanged();
            }
        }
        private global::System.String _orderState;
        partial void OnorderStateChanging(global::System.String value);
        partial void OnorderStateChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_OrderObjects", "OrderObjects")]
        public OrderObjects OrderObjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderObjects>("VotGESOrdersModel.FK_Orders_OrderObjects", "OrderObjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderObjects>("VotGESOrdersModel.FK_Orders_OrderObjects", "OrderObjects").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OrderObjects> OrderObjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OrderObjects>("VotGESOrdersModel.FK_Orders_OrderObjects", "OrderObjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OrderObjects>("VotGESOrdersModel.FK_Orders_OrderObjects", "OrderObjects", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersAccept", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersAccept", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersAccept", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersAccept", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersAccept", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersBan", "Users")]
        public Users Users1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersBan", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersBan", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersBan", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersBan", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersCancel", "Users")]
        public Users Users2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCancel", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCancel", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCancel", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCancel", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersClose", "Users")]
        public Users Users3
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersClose", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersClose", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users3Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersClose", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersClose", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersComplete", "Users")]
        public Users Users4
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersComplete", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersComplete", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users4Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersComplete", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersComplete", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersCreate", "Users")]
        public Users Users5
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCreate", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCreate", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users5Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCreate", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersCreate", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersOpen", "Users")]
        public Users Users6
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersOpen", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersOpen", "Users").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> Users6Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersOpen", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("VotGESOrdersModel.FK_Orders_UsersOpen", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VotGESOrdersModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Users.
        /// </summary>
        /// <param name="userID">Исходное значение свойства userID.</param>
        /// <param name="name">Исходное значение свойства name.</param>
        /// <param name="fullName">Исходное значение свойства fullName.</param>
        /// <param name="allowCreateOrder">Исходное значение свойства allowCreateOrder.</param>
        /// <param name="allowAcceptOrder">Исходное значение свойства allowAcceptOrder.</param>
        /// <param name="allowOpenOrder">Исходное значение свойства allowOpenOrder.</param>
        /// <param name="allowCancelOrder">Исходное значение свойства allowCancelOrder.</param>
        /// <param name="allowCloseOrder">Исходное значение свойства allowCloseOrder.</param>
        /// <param name="allowCompleteOrder">Исходное значение свойства allowCompleteOrder.</param>
        /// <param name="allowExtendOrder">Исходное значение свойства allowExtendOrder.</param>
        /// <param name="allowEditTree">Исходное значение свойства allowEditTree.</param>
        /// <param name="allowEditUsers">Исходное значение свойства allowEditUsers.</param>
        /// <param name="allowEditOrders">Исходное значение свойства allowEditOrders.</param>
        /// <param name="allowAgreeOrders">Исходное значение свойства allowAgreeOrders.</param>
        public static Users CreateUsers(global::System.Int32 userID, global::System.String name, global::System.String fullName, global::System.Boolean allowCreateOrder, global::System.Boolean allowAcceptOrder, global::System.Boolean allowOpenOrder, global::System.Boolean allowCancelOrder, global::System.Boolean allowCloseOrder, global::System.Boolean allowCompleteOrder, global::System.Boolean allowExtendOrder, global::System.Boolean allowEditTree, global::System.Boolean allowEditUsers, global::System.Boolean allowEditOrders, global::System.Boolean allowAgreeOrders)
        {
            Users users = new Users();
            users.userID = userID;
            users.name = name;
            users.fullName = fullName;
            users.allowCreateOrder = allowCreateOrder;
            users.allowAcceptOrder = allowAcceptOrder;
            users.allowOpenOrder = allowOpenOrder;
            users.allowCancelOrder = allowCancelOrder;
            users.allowCloseOrder = allowCloseOrder;
            users.allowCompleteOrder = allowCompleteOrder;
            users.allowExtendOrder = allowExtendOrder;
            users.allowEditTree = allowEditTree;
            users.allowEditUsers = allowEditUsers;
            users.allowEditOrders = allowEditOrders;
            users.allowAgreeOrders = allowAgreeOrders;
            return users;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fullName
        {
            get
            {
                return _fullName;
            }
            set
            {
                OnfullNameChanging(value);
                ReportPropertyChanging("fullName");
                _fullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fullName");
                OnfullNameChanged();
            }
        }
        private global::System.String _fullName;
        partial void OnfullNameChanging(global::System.String value);
        partial void OnfullNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowCreateOrder
        {
            get
            {
                return _allowCreateOrder;
            }
            set
            {
                OnallowCreateOrderChanging(value);
                ReportPropertyChanging("allowCreateOrder");
                _allowCreateOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowCreateOrder");
                OnallowCreateOrderChanged();
            }
        }
        private global::System.Boolean _allowCreateOrder;
        partial void OnallowCreateOrderChanging(global::System.Boolean value);
        partial void OnallowCreateOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowAcceptOrder
        {
            get
            {
                return _allowAcceptOrder;
            }
            set
            {
                OnallowAcceptOrderChanging(value);
                ReportPropertyChanging("allowAcceptOrder");
                _allowAcceptOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowAcceptOrder");
                OnallowAcceptOrderChanged();
            }
        }
        private global::System.Boolean _allowAcceptOrder;
        partial void OnallowAcceptOrderChanging(global::System.Boolean value);
        partial void OnallowAcceptOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowOpenOrder
        {
            get
            {
                return _allowOpenOrder;
            }
            set
            {
                OnallowOpenOrderChanging(value);
                ReportPropertyChanging("allowOpenOrder");
                _allowOpenOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowOpenOrder");
                OnallowOpenOrderChanged();
            }
        }
        private global::System.Boolean _allowOpenOrder;
        partial void OnallowOpenOrderChanging(global::System.Boolean value);
        partial void OnallowOpenOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowCancelOrder
        {
            get
            {
                return _allowCancelOrder;
            }
            set
            {
                OnallowCancelOrderChanging(value);
                ReportPropertyChanging("allowCancelOrder");
                _allowCancelOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowCancelOrder");
                OnallowCancelOrderChanged();
            }
        }
        private global::System.Boolean _allowCancelOrder;
        partial void OnallowCancelOrderChanging(global::System.Boolean value);
        partial void OnallowCancelOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowCloseOrder
        {
            get
            {
                return _allowCloseOrder;
            }
            set
            {
                OnallowCloseOrderChanging(value);
                ReportPropertyChanging("allowCloseOrder");
                _allowCloseOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowCloseOrder");
                OnallowCloseOrderChanged();
            }
        }
        private global::System.Boolean _allowCloseOrder;
        partial void OnallowCloseOrderChanging(global::System.Boolean value);
        partial void OnallowCloseOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowCompleteOrder
        {
            get
            {
                return _allowCompleteOrder;
            }
            set
            {
                OnallowCompleteOrderChanging(value);
                ReportPropertyChanging("allowCompleteOrder");
                _allowCompleteOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowCompleteOrder");
                OnallowCompleteOrderChanged();
            }
        }
        private global::System.Boolean _allowCompleteOrder;
        partial void OnallowCompleteOrderChanging(global::System.Boolean value);
        partial void OnallowCompleteOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowExtendOrder
        {
            get
            {
                return _allowExtendOrder;
            }
            set
            {
                OnallowExtendOrderChanging(value);
                ReportPropertyChanging("allowExtendOrder");
                _allowExtendOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowExtendOrder");
                OnallowExtendOrderChanged();
            }
        }
        private global::System.Boolean _allowExtendOrder;
        partial void OnallowExtendOrderChanging(global::System.Boolean value);
        partial void OnallowExtendOrderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowEditTree
        {
            get
            {
                return _allowEditTree;
            }
            set
            {
                OnallowEditTreeChanging(value);
                ReportPropertyChanging("allowEditTree");
                _allowEditTree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowEditTree");
                OnallowEditTreeChanged();
            }
        }
        private global::System.Boolean _allowEditTree;
        partial void OnallowEditTreeChanging(global::System.Boolean value);
        partial void OnallowEditTreeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowEditUsers
        {
            get
            {
                return _allowEditUsers;
            }
            set
            {
                OnallowEditUsersChanging(value);
                ReportPropertyChanging("allowEditUsers");
                _allowEditUsers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowEditUsers");
                OnallowEditUsersChanged();
            }
        }
        private global::System.Boolean _allowEditUsers;
        partial void OnallowEditUsersChanging(global::System.Boolean value);
        partial void OnallowEditUsersChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowEditOrders
        {
            get
            {
                return _allowEditOrders;
            }
            set
            {
                OnallowEditOrdersChanging(value);
                ReportPropertyChanging("allowEditOrders");
                _allowEditOrders = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowEditOrders");
                OnallowEditOrdersChanged();
            }
        }
        private global::System.Boolean _allowEditOrders;
        partial void OnallowEditOrdersChanging(global::System.Boolean value);
        partial void OnallowEditOrdersChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowAgreeOrders
        {
            get
            {
                return _allowAgreeOrders;
            }
            set
            {
                OnallowAgreeOrdersChanging(value);
                ReportPropertyChanging("allowAgreeOrders");
                _allowAgreeOrders = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowAgreeOrders");
                OnallowAgreeOrdersChanged();
            }
        }
        private global::System.Boolean _allowAgreeOrders;
        partial void OnallowAgreeOrdersChanging(global::System.Boolean value);
        partial void OnallowAgreeOrdersChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersAccept", "Orders")]
        public EntityCollection<Orders> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersAccept", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersAccept", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersBan", "Orders")]
        public EntityCollection<Orders> Orders1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersBan", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersBan", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersCancel", "Orders")]
        public EntityCollection<Orders> Orders2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersCancel", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersCancel", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersClose", "Orders")]
        public EntityCollection<Orders> Orders3
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersClose", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersClose", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersComplete", "Orders")]
        public EntityCollection<Orders> Orders4
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersComplete", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersComplete", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersCreate", "Orders")]
        public EntityCollection<Orders> Orders5
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersCreate", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersCreate", "Orders", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VotGESOrdersModel", "FK_Orders_UsersOpen", "Orders")]
        public EntityCollection<Orders> Orders6
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersOpen", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Orders>("VotGESOrdersModel.FK_Orders_UsersOpen", "Orders", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
